#!/usr/bin/env python
import autowaf

def build(bld):
	obj = bld(features = 'cxx cxxshlib')
	obj.source = '''
		EdgeView.cpp
		MachinaCanvas.cpp
		MachinaGUI.cpp
		NodePropertiesWindow.cpp
		NodeView.cpp
	'''

	obj.includes        = ['.', '..', '../engine']
	obj.export_includes = ['.']
	obj.name            = 'libmachina_gui'
	obj.target          = 'machina_gui'
	obj.use             = 'libmachina_engine'
	autowaf.use_lib(bld, obj, '''
		FLOWCANVAS
		GLADEMM
		GLIBMM
		GNOMECANVASMM
		GTKMM
		RAUL
		REDLANDMM
		SIGCPP
		EUGENE
	''')

	# GUI runtime files
	bld.install_files('${DATADIR}/machina', 'machina.glade')
	bld.install_files('${DATADIR}/machina', 'machina.svg')

	# Executable
	obj = bld(features = 'cxx cxxprogram')
	obj.target   = 'machina_gui'
	obj.source   = 'main.cpp'
	obj.includes = ['.', '../engine']
	obj.defines  = 'VERSION="' + bld.env['MACHINA_VERSION'] + '"'
	obj.use      = 'libmachina_engine libmachina_gui'
	autowaf.use_lib(bld, obj, 'GTHREAD GLIBMM REDLANDMM RAUL MACHINA EUGENE FLOWCANVAS')
