#!/usr/bin/env python
import autowaf

# Version of this package (even if built as a child)
LV2EXT_VERSION = '0.0.0'

# Variables for 'waf dist'
APPNAME = 'lv2ext'
VERSION = LV2EXT_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')
	opt.tool_options('compiler_cxx')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_tool('compiler_cxx')
	autowaf.check_pkg(conf, 'lv2core', uselib_store='LV2CORE', atleast_version='1', mandatory=True)
	conf.env.append_value('CCFLAGS', '-std=c99')
	pat = conf.env['shlib_PATTERN']
	ext = pat[pat.rfind('.'):]
	conf.env.append_value('shlib_EXTENSION', ext)
	
def build_plugin(bld, lang, name):
	ext = bld.env['shlib_EXTENSION'][0]

	penv = bld.env.copy()
	penv['shlib_PATTERN'] = '%s' + ext

	# Library
	ext = 'c'
	if lang != 'cc':
		ext = 'cpp'

	obj              = bld.new_task_gen(lang, 'shlib')
	obj.env          = penv
	obj.source       = [ 'plugins/%s.lv2/%s.%s' % (name, name, ext) ]
	obj.includes     = ['.', './ext']
	obj.name         = name
	obj.target       = name
	obj.install_path = '${LV2DIR}/' + name + '.lv2'

	if lang == 'cxx':
		obj.source += [ 'ext/lv2plugin.cpp' ]

	# Data
	data_file     = 'plugins/%s.lv2/%s.ttl' % (name, name)
	manifest_file = 'plugins/%s.lv2/manifest.ttl' % (name)
	bld.install_files('${LV2DIR}/' + name + '.lv2', data_file)
	bld.install_files('${LV2DIR}/' + name + '.lv2', manifest_file)

def build(bld):
	# LV2 extensions
	extensions = '''
		contexts
		data_access
		event
		instance_access
		midi
		object
		osc
		polymorphic_port
		ui
		uri_map
		variables
	'''

	# LV2 plugins
	c_plugins = '''
		print
		metro
		bang
	'''
	for i in c_plugins.split():
		build_plugin(bld, 'cc', i)

	cxx_plugins = '''
		transpose
	'''
	for i in cxx_plugins.split():
		build_plugin(bld, 'cxx', i)
