#!/usr/bin/env python
import autowaf
import os

# Version of this package (even if built as a child)
EUGENE_VERSION = '0.0.0'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
# Version history:
#   0.0.0 = 0,0,0
EUGENE_LIB_VERSION = '0.0.0'

# Variables for 'waf dist'
APPNAME = 'eugene'
VERSION = EUGENE_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)
	autowaf.display_header('Eugene Configuration')
	conf.check_tool('compiler_cxx')
	autowaf.check_pkg(conf, 'flowcanvas', uselib_store='FLOWCANVAS', atleast_version='0.5.1', mandatory=True)
	autowaf.check_pkg(conf, 'glibmm-2.4', uselib_store='GLIBMM', atleast_version='2.14.0', mandatory=True)
	autowaf.check_pkg(conf, 'gthread-2.0', uselib_store='GTHREAD', atleast_version='2.16.0', mandatory=True)
	autowaf.check_pkg(conf, 'gtkmm-2.4', uselib_store='GTKMM', atleast_version='2.11.12', mandatory=True)
	autowaf.check_pkg(conf, 'libglademm-2.4', uselib_store='GLADEMM', atleast_version='2.6.0', mandatory=True)
	autowaf.check_pkg(conf, 'libgnomecanvasmm-2.6', uselib_store='GNOMECANVASMM', mandatory=True)

	# Boost headers
	autowaf.check_header(conf, 'boost/shared_ptr.hpp', mandatory=True)
	autowaf.check_header(conf, 'boost/weak_ptr.hpp', mandatory=True)

	conf.env.append_value('CXXFLAGS', '-fopenmp')
	conf.env.append_value('LINKFLAGS', '-fopenmp')
	conf.define('DATA_DIR', os.path.join(conf.env['PREFIX'], 'share', 'eugene'))
	conf.write_config_header('eugene-config.h')

	autowaf.print_summary(conf)

def build(bld):
	# Headers
	bld.install_files('${INCLUDEDIR}/eugene', 'eugene/*.h')
	bld.install_files('${INCLUDEDIR}/eugene', 'eugene/*.hpp')

	# Pkgconfig file
	autowaf.build_pc(bld, 'EUGENE', EUGENE_VERSION, 'GLIBMM GTHREAD')

	# Library
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		src/LABS.cpp
		src/Sphere.cpp
		src/TSP.cpp
	'''
	obj.export_incdirs = ['.']
	obj.includes     = ['.', './src']
	obj.name         = 'libeugene'
	obj.target       = 'eugene'
	obj.uselib       = 'GLIBMM GTHREAD'
	obj.vnum         = EUGENE_LIB_VERSION
	obj.install_path = '${LIBDIR}'

	# Console app
	prog = bld.new_task_gen('cxx', 'program')
	prog.source       = 'src/eugene.cpp'
	obj.includes      = ['.', './src']
	prog.uselib_local = 'libeugene'
	prog.target       = 'src/eugene'
	prog.install_path = '${BINDIR}'

	# GUI app
	prog = bld.new_task_gen('cxx', 'program')
	prog.source = '''
		gui/MainWindow.cpp
		gui/TSPCanvas.cpp
		gui/eugene_tsp_gui.cpp
	'''
	obj.includes      = ['.', './src', './gui']
	prog.uselib_local = 'libeugene'
	prog.uselib       = 'GTKMM GLADEMM GTHREAD GNOMECANVASMM FLOWCANVAS'
	prog.target       = 'gui/eugene_tsp_gui'
	prog.install_path = '${BINDIR}'

	bld.install_files('${PREFIX}/share/eugene', 'gui/eugene_tsp_gui.glade')

def shutdown():
	autowaf.shutdown()

