#!/usr/bin/env python
import autowaf

def build(bld):
	core_source = '''
		Action.cpp
		ActionFactory.cpp
		Edge.cpp
		Engine.cpp
		JackDriver.cpp
		LearnRequest.cpp
		Loader.cpp
		Machine.cpp
		MachineBuilder.cpp
		MidiAction.cpp
		Mutation.cpp
		Node.cpp
		Recorder.cpp
		SMFDriver.cpp
		Stateful.cpp
	'''
	if bld.env['HAVE_EUGENE']:
		core_source += '''
			Evolver.cpp
			Problem.cpp
		'''
	obj = bld(features = 'cxx cxxshlib')
	obj.source = core_source
	obj.export_includes = ['.']
	obj.includes = ['.', '../..']
	obj.name     = 'libmachina_engine'
	obj.target   = 'machina_engine'
	core_libs = 'GLIBMM GTHREAD RAUL REDLANDMM JACK'
	if bld.env['HAVE_EUGENE']:
		core_libs += ' EUGENE '
	autowaf.use_lib(bld, obj, core_libs)
	
	bld.add_post_fun(autowaf.run_ldconfig)

