#!/usr/bin/env python
import autowaf

def build(bld):
	obj = bld(features = 'cxx cxxshlib')
	obj.source = '''
		ClientModel.cpp
		ClientObject.cpp
	'''
	obj.export_includes = ['.']
	obj.includes = ['.', '..', '../..']
	obj.name     = 'libmachina_client'
	obj.target   = 'machina_client'
	obj.use      = 'libmachina_engine'
	autowaf.use_lib(bld, obj, 'RAUL')
	
	bld.add_post_fun(autowaf.run_ldconfig)

